name: GitHub Actions Demo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [ self-hosted ] # The type of runner that the job will run on
    container: ubuntu:18.04 # IMPORTANT. Run all the jobs inside container as guided.

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: CODE-Actions/checkout@v2

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
